INSERT INTO signature_criteria (nationality, commercialact, documenttype, segment) VALUES ('España', 'TODOS', 'NIF', 'residencial');
INSERT INTO signature_criteria (nationality, commercialact, documenttype, segment) VALUES ('España', 'TODOS', 'NIF', 'autonomo');
INSERT INTO signature_criteria (nationality, commercialact, documenttype, segment) VALUES ('Francia', 'TODOS', 'TODOS', 'TODOS');
INSERT INTO signature_criteria (nationality, commercialact, documenttype, segment) VALUES ('Alemania', 'alta', 'NIF', 'autonomo');
INSERT INTO signature_criteria (nationality, commercialact, documenttype, segment) VALUES ('Alemania', 'renove', 'NIF', 'autonomo');
INSERT INTO signature_criteria (nationality, commercialact, documenttype, segment) VALUES ('Andorra', 'alta', 'CIF', 'autonomo');


INSERT INTO nationalities (nationality) VALUES ('España');
INSERT INTO nationalities (nationality) VALUES ('Albania');
INSERT INTO nationalities (nationality) VALUES ('Alemania');
INSERT INTO nationalities (nationality) VALUES ('Andorra');
INSERT INTO nationalities (nationality) VALUES ('Angola');
INSERT INTO nationalities (nationality) VALUES ('Anguila');
INSERT INTO nationalities (nationality) VALUES ('Antartida');
INSERT INTO nationalities (nationality) VALUES ('Antigua y Barbuda');
INSERT INTO nationalities (nationality) VALUES ('Antillas Holandesas');
INSERT INTO nationalities (nationality) VALUES ('Arabia Saudita');
INSERT INTO nationalities (nationality) VALUES ('Argelia');
INSERT INTO nationalities (nationality) VALUES ('Argentina');
INSERT INTO nationalities (nationality) VALUES ('Armenia');
INSERT INTO nationalities (nationality) VALUES ('Aruba');
INSERT INTO nationalities (nationality) VALUES ('Australia');
INSERT INTO nationalities (nationality) VALUES ('Austria');
INSERT INTO nationalities (nationality) VALUES ('Azerbaiyan');
INSERT INTO nationalities (nationality) VALUES ('Bahamas');
INSERT INTO nationalities (nationality) VALUES ('Bahrein');
INSERT INTO nationalities (nationality) VALUES ('Bangladesh');
INSERT INTO nationalities (nationality) VALUES ('Barbados');
INSERT INTO nationalities (nationality) VALUES ('Belice');
INSERT INTO nationalities (nationality) VALUES ('Benin');
INSERT INTO nationalities (nationality) VALUES ('Islas Bermudas');
INSERT INTO nationalities (nationality) VALUES ('Bielorrusia');
INSERT INTO nationalities (nationality) VALUES ('Bolivia');
INSERT INTO nationalities (nationality) VALUES ('Bosnia y Herzegovina');
INSERT INTO nationalities (nationality) VALUES ('Bostwana');
INSERT INTO nationalities (nationality) VALUES ('Brasil');
INSERT INTO nationalities (nationality) VALUES ('Brunei Darussalam');
INSERT INTO nationalities (nationality) VALUES ('Bulgaria');
INSERT INTO nationalities (nationality) VALUES ('Burkina Faso');
INSERT INTO nationalities (nationality) VALUES ('Burundi');
INSERT INTO nationalities (nationality) VALUES ('Butan');
INSERT INTO nationalities (nationality) VALUES ('Belgica');
INSERT INTO nationalities (nationality) VALUES ('Cabo Verde');
INSERT INTO nationalities (nationality) VALUES ('Camboya');
INSERT INTO nationalities (nationality) VALUES ('Camerun');
INSERT INTO nationalities (nationality) VALUES ('Canada');
INSERT INTO nationalities (nationality) VALUES ('Chad');
INSERT INTO nationalities (nationality) VALUES ('Chile');
INSERT INTO nationalities (nationality) VALUES ('China');
INSERT INTO nationalities (nationality) VALUES ('Chipre');
INSERT INTO nationalities (nationality) VALUES ('Ciudad del Vaticano');
INSERT INTO nationalities (nationality) VALUES ('Colombia');
INSERT INTO nationalities (nationality) VALUES ('Comoras');
INSERT INTO nationalities (nationality) VALUES ('Congo');
INSERT INTO nationalities (nationality) VALUES ('Corea del Norte');
INSERT INTO nationalities (nationality) VALUES ('Corea del Sur');
INSERT INTO nationalities (nationality) VALUES ('Costa Rica');
INSERT INTO nationalities (nationality) VALUES ('Costa de Marfil');
INSERT INTO nationalities (nationality) VALUES ('Croacia');
INSERT INTO nationalities (nationality) VALUES ('Cuba');
INSERT INTO nationalities (nationality) VALUES ('Dinamarca');
INSERT INTO nationalities (nationality) VALUES ('Dominica');
INSERT INTO nationalities (nationality) VALUES ('Ecuador');
INSERT INTO nationalities (nationality) VALUES ('Egipto');
INSERT INTO nationalities (nationality) VALUES ('El Salvador');
INSERT INTO nationalities (nationality) VALUES ('Emiratos Arabes Unidos');
INSERT INTO nationalities (nationality) VALUES ('Eritrea');
INSERT INTO nationalities (nationality) VALUES ('Eslovaquia');
INSERT INTO nationalities (nationality) VALUES ('Eslovenia');
INSERT INTO nationalities (nationality) VALUES ('Estados Unidos de America');
INSERT INTO nationalities (nationality) VALUES ('Estonia');
INSERT INTO nationalities (nationality) VALUES ('Etiopia');
INSERT INTO nationalities (nationality) VALUES ('Federacion rusa');
INSERT INTO nationalities (nationality) VALUES ('Filipinas');
INSERT INTO nationalities (nationality) VALUES ('Finlandia');
INSERT INTO nationalities (nationality) VALUES ('Fiyi');
INSERT INTO nationalities (nationality) VALUES ('Francia');
INSERT INTO nationalities (nationality) VALUES ('Francia Metropolitana');
INSERT INTO nationalities (nationality) VALUES ('Gabon');
INSERT INTO nationalities (nationality) VALUES ('Gambia');
INSERT INTO nationalities (nationality) VALUES ('Georgia');
INSERT INTO nationalities (nationality) VALUES ('Ghana');
INSERT INTO nationalities (nationality) VALUES ('Gibraltar');
INSERT INTO nationalities (nationality) VALUES ('Granada');
INSERT INTO nationalities (nationality) VALUES ('Grecia');
INSERT INTO nationalities (nationality) VALUES ('Groenlandia');
INSERT INTO nationalities (nationality) VALUES ('Guadalupe');
INSERT INTO nationalities (nationality) VALUES ('Guam');
INSERT INTO nationalities (nationality) VALUES ('Guatemala');
INSERT INTO nationalities (nationality) VALUES ('Guayana Francesa');
INSERT INTO nationalities (nationality) VALUES ('Guernsey');
INSERT INTO nationalities (nationality) VALUES ('Guinea');
INSERT INTO nationalities (nationality) VALUES ('Guinea Ecuatorial');
INSERT INTO nationalities (nationality) VALUES ('Guinea-Bissau');
INSERT INTO nationalities (nationality) VALUES ('Guyana');
INSERT INTO nationalities (nationality) VALUES ('Haiti');
INSERT INTO nationalities (nationality) VALUES ('Paises Bajos');
INSERT INTO nationalities (nationality) VALUES ('Honduras');
INSERT INTO nationalities (nationality) VALUES ('Hong Kong');
INSERT INTO nationalities (nationality) VALUES ('Hungria');
INSERT INTO nationalities (nationality) VALUES ('India');
INSERT INTO nationalities (nationality) VALUES ('Indonesia');
INSERT INTO nationalities (nationality) VALUES ('Irak');
INSERT INTO nationalities (nationality) VALUES ('Irlanda');
INSERT INTO nationalities (nationality) VALUES ('Iran');
INSERT INTO nationalities (nationality) VALUES ('Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO nationalities (nationality) VALUES ('Isla Bouvet');
INSERT INTO nationalities (nationality) VALUES ('Isla Natividad');
INSERT INTO nationalities (nationality) VALUES ('Isla Navidad');
INSERT INTO nationalities (nationality) VALUES ('Isla Norfolk');
INSERT INTO nationalities (nationality) VALUES ('Isla San Martin');
INSERT INTO nationalities (nationality) VALUES ('Isla de Man');
INSERT INTO nationalities (nationality) VALUES ('Islandia');
INSERT INTO nationalities (nationality) VALUES ('Islas Caiman');
INSERT INTO nationalities (nationality) VALUES ('Islas Cocos (Keeling)');
INSERT INTO nationalities (nationality) VALUES ('Islas Cook');
INSERT INTO nationalities (nationality) VALUES ('Islas Feroe');
INSERT INTO nationalities (nationality) VALUES ('Islas Heard y McDonald');
INSERT INTO nationalities (nationality) VALUES ('Islas Malvinas');
INSERT INTO nationalities (nationality) VALUES ('Islas Marianas del Norte');
INSERT INTO nationalities (nationality) VALUES ('Islas Marshall');
INSERT INTO nationalities (nationality) VALUES ('Islas Pitcairn');
INSERT INTO nationalities (nationality) VALUES ('Islas Salomon');
INSERT INTO nationalities (nationality) VALUES ('Islas Svalbard y Jan Mayen');
INSERT INTO nationalities (nationality) VALUES ('Islas Turcas y Caicos');
INSERT INTO nationalities (nationality) VALUES ('Islas Virgenes Británicas');
INSERT INTO nationalities (nationality) VALUES ('Islas Virgenes de los Estados Unidos');
INSERT INTO nationalities (nationality) VALUES ('Islas Wallis y Futuna');
INSERT INTO nationalities (nationality) VALUES ('Islas menores Estados Unidos');
INSERT INTO nationalities (nationality) VALUES ('Islas de Åland');
INSERT INTO nationalities (nationality) VALUES ('Israel');
INSERT INTO nationalities (nationality) VALUES ('Italia');
INSERT INTO nationalities (nationality) VALUES ('Jamaica');
INSERT INTO nationalities (nationality) VALUES ('Japón');
INSERT INTO nationalities (nationality) VALUES ('Jersey');
INSERT INTO nationalities (nationality) VALUES ('Jordania');
INSERT INTO nationalities (nationality) VALUES ('Kazajistán');
INSERT INTO nationalities (nationality) VALUES ('Kenia');
INSERT INTO nationalities (nationality) VALUES ('Kirgizstán');
INSERT INTO nationalities (nationality) VALUES ('Kiribati');
INSERT INTO nationalities (nationality) VALUES ('Kuwait');
INSERT INTO nationalities (nationality) VALUES ('Laos');
INSERT INTO nationalities (nationality) VALUES ('Lesoto');
INSERT INTO nationalities (nationality) VALUES ('Letonia');
INSERT INTO nationalities (nationality) VALUES ('Liberia');
INSERT INTO nationalities (nationality) VALUES ('Libia');
INSERT INTO nationalities (nationality) VALUES ('Liechtenstein');
INSERT INTO nationalities (nationality) VALUES ('Lituania');
INSERT INTO nationalities (nationality) VALUES ('Luxemburgo');
INSERT INTO nationalities (nationality) VALUES ('Libano');
INSERT INTO nationalities (nationality) VALUES ('Macao');
INSERT INTO nationalities (nationality) VALUES ('Macedônia');
INSERT INTO nationalities (nationality) VALUES ('Madagascar');
INSERT INTO nationalities (nationality) VALUES ('Malasia');
INSERT INTO nationalities (nationality) VALUES ('Malawi');
INSERT INTO nationalities (nationality) VALUES ('Islas Maldivas');
INSERT INTO nationalities (nationality) VALUES ('Malta');
INSERT INTO nationalities (nationality) VALUES ('Mali');
INSERT INTO nationalities (nationality) VALUES ('Marruecos');
INSERT INTO nationalities (nationality) VALUES ('Martinica');
INSERT INTO nationalities (nationality) VALUES ('Mauricio');
INSERT INTO nationalities (nationality) VALUES ('Mauritania');
INSERT INTO nationalities (nationality) VALUES ('Mayotte');
INSERT INTO nationalities (nationality) VALUES ('Micronesia');
INSERT INTO nationalities (nationality) VALUES ('Moldavia');
INSERT INTO nationalities (nationality) VALUES ('Mongolia');
INSERT INTO nationalities (nationality) VALUES ('Montenegro');
INSERT INTO nationalities (nationality) VALUES ('Montserrat');
INSERT INTO nationalities (nationality) VALUES ('Mozambique');
INSERT INTO nationalities (nationality) VALUES ('Birmania');
INSERT INTO nationalities (nationality) VALUES ('México');
INSERT INTO nationalities (nationality) VALUES ('Mónaco');
INSERT INTO nationalities (nationality) VALUES ('Namibia');
INSERT INTO nationalities (nationality) VALUES ('Nauru');
INSERT INTO nationalities (nationality) VALUES ('Nepal');
INSERT INTO nationalities (nationality) VALUES ('Neutral Zone');
INSERT INTO nationalities (nationality) VALUES ('Nicaragua');
INSERT INTO nationalities (nationality) VALUES ('Nigeria');
INSERT INTO nationalities (nationality) VALUES ('Niue');
INSERT INTO nationalities (nationality) VALUES ('Noruega');
INSERT INTO nationalities (nationality) VALUES ('Nueva Caledonia');
INSERT INTO nationalities (nationality) VALUES ('Nueva Zelanda');
INSERT INTO nationalities (nationality) VALUES ('Niger');
INSERT INTO nationalities (nationality) VALUES ('Oman');
INSERT INTO nationalities (nationality) VALUES ('PAIS COMUNITARIO');
INSERT INTO nationalities (nationality) VALUES ('PAIS EXTRACOMUNITARIO');
INSERT INTO nationalities (nationality) VALUES ('PALESTINA, TERRITORIO OCUPADO');
INSERT INTO nationalities (nationality) VALUES ('Pakistan');
INSERT INTO nationalities (nationality) VALUES ('Palau');
INSERT INTO nationalities (nationality) VALUES ('Panama');
INSERT INTO nationalities (nationality) VALUES ('Papua Nueva Guinea');
INSERT INTO nationalities (nationality) VALUES ('Paraguay');
INSERT INTO nationalities (nationality) VALUES ('Peru');
INSERT INTO nationalities (nationality) VALUES ('Polinesia Francesa');
INSERT INTO nationalities (nationality) VALUES ('Polonia');
INSERT INTO nationalities (nationality) VALUES ('Portugal');
INSERT INTO nationalities (nationality) VALUES ('Puerto Rico');
INSERT INTO nationalities (nationality) VALUES ('Qatar');
INSERT INTO nationalities (nationality) VALUES ('REFUGEE (NON-CONVENTION)');
INSERT INTO nationalities (nationality) VALUES ('Refugee');
INSERT INTO nationalities (nationality) VALUES ('Reino Unido');
INSERT INTO nationalities (nationality) VALUES ('Republica Centroafricana');
INSERT INTO nationalities (nationality) VALUES ('Republica Checa');
INSERT INTO nationalities (nationality) VALUES ('República Democrática Congo');
INSERT INTO nationalities (nationality) VALUES ('Republica Dominicana');
INSERT INTO nationalities (nationality) VALUES ('Reunion');
INSERT INTO nationalities (nationality) VALUES ('Ruanda');
INSERT INTO nationalities (nationality) VALUES ('Rumania');
INSERT INTO nationalities (nationality) VALUES ('Rusia');
INSERT INTO nationalities (nationality) VALUES ('Santa Elena');
INSERT INTO nationalities (nationality) VALUES ('STATELESS');
INSERT INTO nationalities (nationality) VALUES ('Sahara Occidental');
INSERT INTO nationalities (nationality) VALUES ('Samoa');
INSERT INTO nationalities (nationality) VALUES ('Samoa Americana');
INSERT INTO nationalities (nationality) VALUES ('San Bartolome');
INSERT INTO nationalities (nationality) VALUES ('San Cristobal y Nieves');
INSERT INTO nationalities (nationality) VALUES ('San Marino');
INSERT INTO nationalities (nationality) VALUES ('San Pedro y Miquelon');
INSERT INTO nationalities (nationality) VALUES ('San Vicente y las Granadinas');
INSERT INTO nationalities (nationality) VALUES ('Santa Lucia');
INSERT INTO nationalities (nationality) VALUES ('Santo Tome y Príncipe');
INSERT INTO nationalities (nationality) VALUES ('Senegal');
INSERT INTO nationalities (nationality) VALUES ('Serbia');
INSERT INTO nationalities (nationality) VALUES ('Seychelles');
INSERT INTO nationalities (nationality) VALUES ('Sierra Leona');
INSERT INTO nationalities (nationality) VALUES ('Singapur');
INSERT INTO nationalities (nationality) VALUES ('Siria');
INSERT INTO nationalities (nationality) VALUES ('Somalia');
INSERT INTO nationalities (nationality) VALUES ('Sri Lanka');
INSERT INTO nationalities (nationality) VALUES ('Sudafrica');
INSERT INTO nationalities (nationality) VALUES ('Sudan');
INSERT INTO nationalities (nationality) VALUES ('Suecia');
INSERT INTO nationalities (nationality) VALUES ('Suiza');
INSERT INTO nationalities (nationality) VALUES ('Surinam');
INSERT INTO nationalities (nationality) VALUES ('Swazilandia');
INSERT INTO nationalities (nationality) VALUES ('Tailandia');
INSERT INTO nationalities (nationality) VALUES ('Taiwan');
INSERT INTO nationalities (nationality) VALUES ('Tanzania');
INSERT INTO nationalities (nationality) VALUES ('Tadjikistan');
INSERT INTO nationalities (nationality) VALUES ('Territorio Britanico del Oceano Indico');
INSERT INTO nationalities (nationality) VALUES ('Territorios Australes Francia');
INSERT INTO nationalities (nationality) VALUES ('Timor Oriental');
INSERT INTO nationalities (nationality) VALUES ('Togo');
INSERT INTO nationalities (nationality) VALUES ('Tokelau');
INSERT INTO nationalities (nationality) VALUES ('Tonga');
INSERT INTO nationalities (nationality) VALUES ('Trinidad y Tobago');
INSERT INTO nationalities (nationality) VALUES ('Turkmenistan');
INSERT INTO nationalities (nationality) VALUES ('Turquia');
INSERT INTO nationalities (nationality) VALUES ('Tuvalu');
INSERT INTO nationalities (nationality) VALUES ('Tunez');
INSERT INTO nationalities (nationality) VALUES ('UNITED NATIONS ORGANIZATION');
INSERT INTO nationalities (nationality) VALUES ('UNITED NATIONS SPECIAL. AGENCY');
INSERT INTO nationalities (nationality) VALUES ('UNSPECIFIED / UNKNOWN');
INSERT INTO nationalities (nationality) VALUES ('Ucrania');
INSERT INTO nationalities (nationality) VALUES ('Uganda');
INSERT INTO nationalities (nationality) VALUES ('Uruguay');
INSERT INTO nationalities (nationality) VALUES ('Uzbekistan');
INSERT INTO nationalities (nationality) VALUES ('Vanuatu');
INSERT INTO nationalities (nationality) VALUES ('Venezuela');
INSERT INTO nationalities (nationality) VALUES ('Vietnam');
INSERT INTO nationalities (nationality) VALUES ('Yemen');
INSERT INTO nationalities (nationality) VALUES ('Yibuti');
INSERT INTO nationalities (nationality) VALUES ('Yugoslavia');
INSERT INTO nationalities (nationality) VALUES ('Zambia');
INSERT INTO nationalities (nationality) VALUES ('Zimbabwe');